### ISSUE TITLE
TypeError: fetch failed

### ISSUE THREAD

**Issue by mohtashima1** [tpiros/jamstack-training-films-ui#3]
error - TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetcher (webpack-internal:///./lib/api.js:10:20)
    at async getServerSideProps (webpack-internal:///./pages/profile.js:145:30) {
  cause: Error: connect ECONNREFUSED ::1:1337
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 1337
  },
  page: '/profile'
}

**Comment by shrutilenka** [comment]
i too face the same issue

**Comment by shrutilenka** [comment]
@mohtashima1 hi there, i faced the same issue but i sucessfully resolved it .
step1. open your windows terminal and write command "ipconfig",copy your ipv4 address, paste that in place of "localhost" in env file
if still the issue isn't resolved ,change the film.js file code for filmList 👍🏻
----->
![image](https://github.com/tpiros/jamstack-training-films-ui/assets/96660357/486839c7-ca45-4951-a96d-2587237956f4)

---->
u can also change the film.js in component folder
--->

![image](https://github.com/tpiros/jamstack-training-films-ui/assets/96660357/32541c8f-43b1-4826-aef6-f0d58dbe5608)

hope it helps </>
